name: Secret Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  secret-scanning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@v3
        with:
          scan_type: github
          repo: ${{ github.repository }}
          branches: main
          
      - name: Upload TruffleHog report
        uses: actions/upload-artifact@v2
        with:
          name: trufflehog-report
          path: ./trufflehog_report.json
